services:

  searxng:
    container_name: searxng
    build: .
    restart: unless-stopped
    ports:
      - "8888:8080"
    volumes:
      - ./data:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://127.0.0.1:8888/
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"